### ISSUE TITLE
generation fiche récapitulative de choix

### ISSUE THREAD

**Issue by SoniaASSAM** [Raouf16/teach_spreadsheets#14]

**Comment by Raouf16** [comment]
I have to help Sonia in the function that generate the "fiche agrégé", some bugs to fix and developments to do

**Comment by SoniaASSAM** [comment]
With Katia, we read the generated preferences and teachers csv files and stocked it into Spark DataFrame. So we add Spark core and Sparke SQL dependencies on the pom.xml file.  The code is in **model.utils.generating.Generating.java**
