### ISSUE TITLE
SWT

### ISSUE THREAD

**Issue by SellamNathan** [Raouf16/teach_spreadsheets#16]
We have to documentate in SWT to replace JAVA FX.

**Comment by Hayaco** [comment]
We will make a interface with SWT. But we don't know if we will have enough time to finish the interface.

**Comment by SellamNathan** [comment]
The code is in the class swt.java. We don't create a package because we had problems with git

**Comment by Hayaco** [comment]
Finally we choose give up the interface with swt because of lack of time.
