### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by SoniaASSAM** [Raouf16/teach_spreadsheets#3]
Creating a GUI with JavaFX

**Comment by SoniaASSAM** [comment]
Creating a formular with JavaFx that will be used by the user to insert his personal informations.

**Comment by SoniaASSAM** [comment]
Creating Preferences user interface

**Comment by Raouf16** [comment]
With Sonia we work to connect the GUI with the function that reads the ODS content, in order to show the courses when the user choice the subject

**Comment by Raouf16** [comment]
We have to resolve some problems on the GUI, and make it up in version to take into account the new code improvements

**Comment by SoniaASSAM** [comment]
Teachers can enter its informations and preferences via the GUI. The put information are stored in CSV file, and transcribing in Excel file.

**Comment by Raouf16** [comment]
I have to develop the GUI, create a main menu and try to do better than @Sonia did (It will be hard ;))

**Comment by Raouf16** [comment]
I have to develop the GUI, create a main menu and try to do better than @Sonia did (It will be hard ;))
